### ISSUE TITLE
bash syntax highlighting error on reproducible-research/renv/renv-containers

### ISSUE THREAD

**Issue by da5nsy** [alan-turing-institute/the-turing-way#2639]
This error occurs on local build:
```
the-turing-way\book\website\reproducible-research\renv\renv-containers.md:550: WARNING: Could not lex literal_block as "bash". Highlighting skipped.
```

I suspect it is because of this: https://github.com/sphinx-doc/sphinx/issues/4098 on this line: `cat: can't open '/shadow': Permission denied`
but I don't know the code/language well enough to fix it.

Do you have capacity to look into this @JimMadge?

---

Part of #2611

**Comment by JimMadge** [comment]
Happy to look at this. However, the book fails to build for me locally before that warning is raised at 92951adb. Python 3.10.7

**Comment by da5nsy** [comment]
Hmm curious! Build fine locally for me with python 3.10.4, and conda only goes up to 3.10.6 so I can't currently replicate your issue with 3.10.7.

**Comment by JimMadge** [comment]
I have the same error on 3.10.4 and 3.9.14.

<details>

```none
Exception occurred:
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 953, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
The full traceback has been saved in /tmp/sphinx-err-5epqes8h.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_client/channels.py", line 224, in get_msg
    ready = await self.socket.poll(timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_book/sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/myst_nb/parser.py", line 67, in parse
    ntbk = generate_notebook_outputs(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/myst_nb/execution.py", line 137, in generate_notebook_outputs
    result = single_nb_execution(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 953, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_book/cli/main.py", line 323, in build
    builder_specific_actions(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_book/cli/main.py", line 531, in builder_specific_actions
    raise RuntimeError(_message_box(msg, color="red", doprint=False)) from result
RuntimeError: 
===============================================================================

There was an error in building your book. Look above for the cause.

===============================================================================

```
</details>

And the log file

<details>

```bash
vagrant@ubuntu2204:~/the-turing-way/book/website$ cat /tmp/sphinx-err-5epqes8h.log 
# Sphinx version: 4.5.0
# Python version: 3.10.4 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.2
# Last messages:
#   reading sources... [ 55%] venv/lib/python3.10/site-packages/latexcodec-2.0.1.dist-info/AUTHORS
#   reading sources... [ 55%] venv/lib/python3.10/site-packages/latexcodec-2.0.1.dist-info/LICENSE
#   reading sources... [ 55%] venv/lib/python3.10/site-packages/matplotlib/backends/web_backend/nbagg_uat
#   Executing: venv/lib/python3.10/site-packages/matplotlib/backends/web_backend/nbagg_uat in: /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/matplotlib/backends/web_backend
#   reading sources... [ 55%] venv/lib/python3.10/site-packages/mdit_py_plugins/container/README
#   reading sources... [ 55%] venv/lib/python3.10/site-packages/mdit_py_plugins/deflist/README
#   reading sources... [ 56%] venv/lib/python3.10/site-packages/mdit_py_plugins/texmath/README
#   reading sources... [ 56%] venv/lib/python3.10/site-packages/mistune-0.8.4.dist-info/DESCRIPTION
#   reading sources... [ 56%] venv/lib/python3.10/site-packages/nbclient/tests/files/Autokill
#   Executing: venv/lib/python3.10/site-packages/nbclient/tests/files/Autokill in: /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/tests/files
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/alabaster/__init__.py
#   sphinx_togglebutton (0.3.2) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_togglebutton/__init__.py
#   sphinx_copybutton (0.5.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_copybutton/__init__.py
#   myst_nb (0.13.2) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/myst_nb/__init__.py
#   jupyter_book (0.13.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_book/__init__.py
#   sphinx_thebe (0.1.2) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_thebe/__init__.py
#   sphinx_comments (0.0.3) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_comments/__init__.py
#   sphinx_external_toc (0.2.4) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_external_toc/__init__.py
#   sphinx.ext.intersphinx (4.5.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/ext/intersphinx.py
#   sphinx_design (0.1.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_design/__init__.py
#   sphinx_book_theme (unknown version) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_book_theme/__init__.py
#   sphinxcontrib.bibtex (2.5.0) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinxcontrib/bibtex/__init__.py
#   sphinx_jupyterbook_latex (unknown version) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx_jupyterbook_latex/__init__.py
#   pydata_sphinx_theme (unknown version) from /home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/pydata_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 730, in _async_poll_for_reply
    msg = await ensure_async(self.kc.shell_channel.get_msg(timeout=new_timeout))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 96, in ensure_async
    result = await obj
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_client/channels.py", line 224, in get_msg
    ready = await self.socket.poll(timeout)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 949, in async_execute_cell
    exec_reply = await self.task_poll_for_reply
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_book/sphinx.py", line 167, in build_sphinx
    app.build(force_all, filenames)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/myst_nb/parser.py", line 67, in parse
    ntbk = generate_notebook_outputs(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/myst_nb/execution.py", line 137, in generate_notebook_outputs
    result = single_nb_execution(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/vagrant/the-turing-way/book/website/venv/lib/python3.10/site-packages/nbclient/client.py", line 953, in async_execute_cell
    raise DeadKernelError("Kernel died")
nbclient.exceptions.DeadKernelError: Kernel died
```

</details>

**Comment by da5nsy** [comment]
Hi @JimMadge - I did as fresh a build as I could (new conda env, new git clone) and everything worked for me 🤷 

- Made a fresh conda env: `conda create -n py3p10p4 python=3.10.4`  
- Activated: `conda activate py3p10p4`  
- Then installed jupyter-book: `conda install -c conda-forge jupyter-book`  
- Then got a fresh clone of the turing way: `git clone https://github.com/alan-turing-institute/the-turing-way.git`  
- Navigated to the right location to build: `cd the-turing-way/book`  
- Then built the book: `jupyter-book build website`  
- Result:  
  ```
  Running Jupyter-Book v0.13.1
  Source Folder: C:\Users\cege-user\the-turing-way\book\website
  Config Path: C:\Users\cege-user\the-turing-way\book\website\_config.yml
  Output Path: C:\Users\cege-user\the-turing-way\book\website\_build\html
  ←[01mRunning Sphinx v4.5.0←[39;49;00m
  ←[01mloading translations [en]... ←[39;49;00mdone
  ←[01mmaking output directory... ←[39;49;00mdone
  [etoc] Changing master_doc to 'welcome'
  checking bibtex cache... out of date
  parsing bibtex file C:\Users\cege-user\the-turing-way\book\website\_bibliography\references.bib... parsed 132 entries
  ←[01mmyst v0.15.2:←[39;49;00m MdParserConfig(renderer='sphinx', commonmark_only=False, enable_extensions=['colon_fence', 'dollarmath', 'linkify', 'substitution', 'tasklist'], dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', disable_syntax=[], url_schemes=['mailto', 'http', 'https'], heading_anchors=None, heading_slug_func=None, html_meta=[], footnote_transition=True, substitutions=[], sub_delimiters=['{', '}'], words_per_minute=200)
  ←[01mbuilding [mo]: ←[39;49;00mtargets for 0 po files that are out of date
  ←[01mbuilding [html]: ←[39;49;00mtargets for 317 source files that are out of date
  ←[01mupdating environment: ←[39;49;00m[new config] 317 added, 0 changed, 0 removed
  ←[01mreading sources... ←[39;49;00m[100%] ←[35mwelcome←[39;49;00m                                              00m00m00m39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\community-handbook.md:: WARNING: toctree contains reference to nonexisting document 'community-handbook/contributing' [etoc.ref]←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\project-design\sdp\types.md:2: WARNING: Non-consecutive header level increase; 0 to 2 [myst.header]←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\project-design\sdpm\informed.md:2: WARNING: Non-consecutive header level increase; 0 to 3 [myst.header]←[39;49;00m
  ←[31mC:\Users\cege-user\the-turing-way\book\website\reproducible-research\open\open-access.md:106: ERROR: Directive 'figure': Invalid options YAML: while scanning a simple key
    in "<unicode string>", line 4, column 1:
      The **gold and diamond** routes  ...
      ^
  could not find expected ':'
    in "<unicode string>", line 5, column 1:
  
      ^
  
  ---
  height: 500px
  name: routes-to-OA
  alt: An image of a train showing the routes to open access publishing. The green route is signalled as free and shows a preprint server at the start of the journey and self archive at the end.
  The **gold and diamond** routes are signalled as author pay and funder or institution pay and show the publish in an open access journal part of the journey.
  ---
  Routes to publishing openly.
  _The Turing Way_ project illustration by Scriberia. Used under a CC-BY 4.0 licence. Original version on Zenodo. [http://doi.org/10.5281/zenodo.5706310](http://doi.org/10.5281/zenodo.5706310)←[39;49;00m
  ←[01mlooking for now-outdated files... ←[39;49;00mnone found
  ←[01mpickling environment... ←[39;49;00mdone
  ←[01mchecking consistency... ←[39;49;00m←[91mC:\Users\cege-user\the-turing-way\book\website\communication\new-articles.md: WARNING: document isn't included in any toctree←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\contributing\contributing-templates.md: WARNING: document isn't included in any toctree←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\contributing\contributing-workflow.md: WARNING: document isn't included in any toctree←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\figures\_figure-list.md: WARNING: document isn't included in any toctree←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\project-design\sdp\pd-sdp-private-learning.md: WARNING: document isn't included in any toctree←[39;49;00m
  done
  ←[01mpreparing documents... ←[39;49;00mdone
  ←[01mwriting output... ←[39;49;00m[100%] ←[32mwelcome←[39;49;00m                                               0m00m00m39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\collaboration\research-infrastructure-roles\data-steward.md:53: WARNING: undefined label: cl-infrastructure-datastewards-support←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\communication\new-articles.md:19: WARNING: undefined label: chapter-label←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\communication\peer-review\peer-review-overview.md:14: WARNING: undefined label: rr-open-access-whatis-publishing←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\acknowledgement.md:19: WARNING: undefined label: contributors-record-contributors←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\acknowledgement\acknowledgement-members.md:12: WARNING: undefined label: contributors-record-contributors←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\community-handbook\acknowledgement\acknowledgement-record.md:4: WARNING: undefined label: contributors-record-contributors←[39;49;00m
  ←[91mC:\Users\cege-user\the-turing-way\book\website\reproducible-research\renv\renv-containers.md:550: WARNING: Could not lex literal_block as "bash". Highlighting skipped.←[39;49;00m
  ←[01mgenerating indices... ←[39;49;00mgenindex done
  ←[01mwriting additional pages... ←[39;49;00msearch done
  ←[01mcopying images... ←[39;49;00m[100%] ←[33mfigures/theturingway-chapters.jpg←[39;49;00m
  ←[01mcopying static files... ←[39;49;00mdone
  ←[01mcopying extra files... ←[39;49;00mdone
  ←[01mdumping search index in English (code: en)... ←[39;49;00mdone
  ←[01mdumping object inventory... ←[39;49;00mdone
  ←[01mbuild succeeded, 16 warnings.←[39;49;00m
  
  The HTML pages are in website\_build\html.
  [etoc] missing index.html written as redirect to 'welcome.html'
  
  ←[92m===============================================================================←[0m
  
  Finished generating HTML for book.
  Your book's HTML pages are here:
      website\_build\html\
  You can look at your book by opening this file in a browser:
      website\_build\html\index.html
  Or paste this line directly into your browser bar:
      file://C:\Users\cege-user\the-turing-way\book\website\_build\html\index.html
  
  ←[92m===============================================================================←[0m
  ```
- *(checked conda and jupyter book version)*:   
  ```
  (py3p10p4) C:\Users\cege-user\the-turing-way\book>conda --version
  conda 22.9.0

  (py3p10p4) C:\Users\cege-user\the-turing-way\book>jupyter-book --version
  Jupyter Book      : 0.13.1
  External ToC      : 0.2.4
  MyST-Parser       : 0.15.2
  MyST-NB           : 0.13.2
  Sphinx Book Theme : 0.3.3
  Jupyter-Cache     : 0.4.3
  NbClient          : 0.5.13
 ```

**Comment by JimMadge** [comment]
@da5nsy I've had another look. Seems like a strange edge case when the virtual environment is located in the `book/website` directory :confused:. I've opened an issue #2670.
