### ISSUE TITLE
ImportError: DLL load failed while setting up local build

### ISSUE THREAD

**Issue by RealRichi3** [alan-turing-institute/the-turing-way#2980]
### Summary

I followed the guide in #2978, to create a local build i ran `python -m pathways.main pathways` but i keep getting this error
```bash
(main-bio) PS C:\Users\ADMIN\Desktop\Main\Repos\turing-way\bio-Turing-Way> python -m pathways.main pathways master
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ADMIN\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ADMIN\anaconda3\scripts\jupyter-book.exe\__main__.py", line 4, in <module>
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_book\cli\main.py", line 17, in <module>    from jupyter_book.utils import _error, _message_box
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_book\utils.py", line 4, in <module>
    from jupyter_client.kernelspec import find_kernel_specs
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_client\__init__.py", line 8, in <module>
    from .asynchronous import AsyncKernelClient  # noqa
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_client\asynchronous\__init__.py", line 1, in <module>
    from .client import AsyncKernelClient  # noqa
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_client\asynchronous\client.py", line 6, in <module>
    from jupyter_client.channels import HBChannel
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\jupyter_client\channels.py", line 12, in <module>
    import zmq.asyncio
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\zmq\__init__.py", line 103, in <module>
    from zmq import backend
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
  File "C:\Users\ADMIN\anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\ADMIN\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: DLL load failed while importing _device: The specified module could not be found.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ADMIN\anaconda3\envs\main-bio\Lib\site-packages\pathways\main.py", line 177, in <module>
    main(sys.argv[1:])  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ADMIN\anaconda3\envs\main-bio\Lib\site-packages\pathways\main.py", line 108, in main
    arg_dict.pop("func")(**arg_dict)
  File "C:\Users\ADMIN\anaconda3\envs\main-bio\Lib\site-packages\pathways\main.py", line 84, in pathways
    run(["jupyter-book", "build", new_path], check=True)
  File "C:\Users\ADMIN\anaconda3\envs\main-bio\Lib\subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['jupyter-book', 'build', WindowsPath('master_copy')]' returned non-zero exit status 1.
(main-bio) PS C:\Users\ADMIN\Desktop\Main\Repos\turing-way\bio-Turing-Way>
```

I found this solution online, i was about missing DLL files, i downloaded them but still same result
https://stackoverflow.com/questions/20201868/importerror-dll-load-failed-the-specified-module-could-not-be-found/20230455

### What needs to be done?
- [ ] *Complete Local build*

### Who can help?
@malvikasharan 

---

**Comment by RealRichi3** [comment]
### Update 
I restarted the whole process, i encountered similar issue but i fixed it by running

```yaml
pip install "charset-normalizer<2.0"
pip install "markupsafe<2.0"
pip install "jinja2<3.0.0"
pip install importlib_resources
```

the python version i'm using is 3.8.16, I'm not sure if the version will matter incase someone else encounters the same issue

**Comment by malvikasharan** [comment]
Thanks for raising this @RealRichi3. Let's come back to this next week to see if any other error arises. Thanks for adding the solution as well.
